In [33]:

import json
import os
import pandas as pd
from pathlib import Path
from openai import OpenAI

In [34]:

# ── Paths ─────────────────────────────────────────────────────────────────────

ROOT      = Path("../")
JSON_PATH = ROOT / "data" / "yt_data" / "dance_youtube_data.json"
CSV_PATH  = ROOT / "data" / "yt_data" / "dance_videos.csv"
KEY_PATH  = ROOT / "data" / "GPT4oKEY.txt"

# OpenRouter key — compatible with the openai SDK via base_url override
api_key = KEY_PATH.read_text(encoding="utf-8").strip()
client = OpenAI(
    api_key=api_key,
    base_url="https://openrouter.ai/api/v1",
)
MODEL = "openai/gpt-4o-mini"
print(f"Client ready → {MODEL}")

Client ready → openai/gpt-4o-mini

In [35]:

# ── Load comments from JSON ────────────────────────────────────────────────────
with JSON_PATH.open("r", encoding="utf-8") as f:
    data = json.load(f)

# Flatten into a list of {video_id, text} dicts
comment_rows = []
for entry in data.values():
    for video in entry.get("videos", []):
        video_id = (
            video.get("basic_info", {}).get("video_id")
            or video.get("comprehensive_info", {}).get("video_id")
        )
        for comment in video.get("comments", []):
            text = str(comment.get("text", "")).strip()
            if text and video_id:
                comment_rows.append({"video_id": video_id, "text": text})

comments_df = pd.DataFrame(comment_rows)
print(f"Total comments loaded: {len(comments_df)}")
print(f"Unique videos:         {comments_df['video_id'].nunique()}")
comments_df.head(3)

Total comments loaded: 3757
Unique videos:         403

      video_id                                               text
0  LH_EyxsupRE  Learning tap was my secret childhood dream. I ...
1  LH_EyxsupRE  Me at 3PM: I should really spend my night stud...
2  LH_EyxsupRE  Wow... i took a class and i learned more in th...

In [36]:

# ── Sentiment function using OpenRouter ───────────────────────────────────────

def score_comment(text: str) -> tuple[str, float]:
    """Returns (label, score) for a single comment. label: POSITIVE/NEUTRAL/NEGATIVE, score: 1/0/-1."""
    response = client.chat.completions.create(
        model=MODEL,
        temperature=0.0,
        messages=[
            {
                "role": "system",
                "content": (
                    "Classify the sentiment of a YouTube comment about a dance video. "
                    "Reply with exactly one word: POSITIVE, NEUTRAL, or NEGATIVE."
                ),
            },
            {"role": "user", "content": text},
        ],
    )
    label = response.choices[0].message.content.strip().upper()
    if label not in ("POSITIVE", "NEUTRAL", "NEGATIVE"):
        label = "NEUTRAL"
    score_map = {"POSITIVE": 1.0, "NEUTRAL": 0.0, "NEGATIVE": -1.0}
    return label, score_map[label]

print("Sentiment function ready.")

Sentiment function ready.

In [37]:

# ── Run sentiment on every comment ────────────────────────────────────────────

sentiments = []
texts = comments_df["text"].tolist()

for idx, text in enumerate(texts):
    label, score = score_comment(text)
    sentiments.append({"label": label, "score": score})

    if (idx + 1) % 10 == 0:
        print(f"Processed {idx + 1} / {len(texts)} comments...")

print(f"\nDone — {len(texts)} comments processed.")

comments_df["sentiment_label"] = [s["label"] for s in sentiments]
comments_df["score"]           = [s["score"] for s in sentiments]
comments_df.head(5)

Processed 10 / 3757 comments...
Processed 20 / 3757 comments...
Processed 30 / 3757 comments...
Processed 40 / 3757 comments...
Processed 50 / 3757 comments...
Processed 60 / 3757 comments...
Processed 70 / 3757 comments...
Processed 80 / 3757 comments...
Processed 90 / 3757 comments...
Processed 100 / 3757 comments...
Processed 110 / 3757 comments...
Processed 120 / 3757 comments...
Processed 130 / 3757 comments...
Processed 140 / 3757 comments...
Processed 150 / 3757 comments...
Processed 160 / 3757 comments...
Processed 170 / 3757 comments...
Processed 180 / 3757 comments...
Processed 190 / 3757 comments...
Processed 200 / 3757 comments...
Processed 210 / 3757 comments...
Processed 220 / 3757 comments...
Processed 230 / 3757 comments...
Processed 240 / 3757 comments...
Processed 250 / 3757 comments...
Processed 260 / 3757 comments...
Processed 270 / 3757 comments...
Processed 280 / 3757 comments...
Processed 290 / 3757 comments...
Processed 300 / 3757 comments...
Processed 310 / 3757 comments...
Processed 320 / 3757 comments...
Processed 330 / 3757 comments...
Processed 340 / 3757 comments...
Processed 350 / 3757 comments...
Processed 360 / 3757 comments...
Processed 370 / 3757 comments...
Processed 380 / 3757 comments...
Processed 390 / 3757 comments...
Processed 400 / 3757 comments...
Processed 410 / 3757 comments...
Processed 420 / 3757 comments...
Processed 430 / 3757 comments...
Processed 440 / 3757 comments...
Processed 450 / 3757 comments...
Processed 460 / 3757 comments...
Processed 470 / 3757 comments...
Processed 480 / 3757 comments...
Processed 490 / 3757 comments...
Processed 500 / 3757 comments...
Processed 510 / 3757 comments...
Processed 520 / 3757 comments...
Processed 530 / 3757 comments...
Processed 540 / 3757 comments...
Processed 550 / 3757 comments...
Processed 560 / 3757 comments...
Processed 570 / 3757 comments...
Processed 580 / 3757 comments...
Processed 590 / 3757 comments...
Processed 600 / 3757 comments...
Processed 610 / 3757 comments...
Processed 620 / 3757 comments...
Processed 630 / 3757 comments...
Processed 640 / 3757 comments...
Processed 650 / 3757 comments...
Processed 660 / 3757 comments...
Processed 670 / 3757 comments...
Processed 680 / 3757 comments...
Processed 690 / 3757 comments...
Processed 700 / 3757 comments...
Processed 710 / 3757 comments...
Processed 720 / 3757 comments...
Processed 730 / 3757 comments...
Processed 740 / 3757 comments...
Processed 750 / 3757 comments...
Processed 760 / 3757 comments...
Processed 770 / 3757 comments...
Processed 780 / 3757 comments...
Processed 790 / 3757 comments...
Processed 800 / 3757 comments...
Processed 810 / 3757 comments...
Processed 820 / 3757 comments...
Processed 830 / 3757 comments...
Processed 840 / 3757 comments...
Processed 850 / 3757 comments...
Processed 860 / 3757 comments...
Processed 870 / 3757 comments...
Processed 880 / 3757 comments...
Processed 890 / 3757 comments...
Processed 900 / 3757 comments...
Processed 910 / 3757 comments...
Processed 920 / 3757 comments...
Processed 930 / 3757 comments...
Processed 940 / 3757 comments...
Processed 950 / 3757 comments...
Processed 960 / 3757 comments...
Processed 970 / 3757 comments...
Processed 980 / 3757 comments...
Processed 990 / 3757 comments...
Processed 1000 / 3757 comments...
Processed 1010 / 3757 comments...
Processed 1020 / 3757 comments...
Processed 1030 / 3757 comments...
Processed 1040 / 3757 comments...
Processed 1050 / 3757 comments...
Processed 1060 / 3757 comments...
Processed 1070 / 3757 comments...
Processed 1080 / 3757 comments...
Processed 1090 / 3757 comments...
Processed 1100 / 3757 comments...
Processed 1110 / 3757 comments...
Processed 1120 / 3757 comments...
Processed 1130 / 3757 comments...
Processed 1140 / 3757 comments...
Processed 1150 / 3757 comments...
Processed 1160 / 3757 comments...
Processed 1170 / 3757 comments...
Processed 1180 / 3757 comments...
Processed 1190 / 3757 comments...
Processed 1200 / 3757 comments...
Processed 1210 / 3757 comments...
Processed 1220 / 3757 comments...
Processed 1230 / 3757 comments...
Processed 1240 / 3757 comments...
Processed 1250 / 3757 comments...
Processed 1260 / 3757 comments...
Processed 1270 / 3757 comments...
Processed 1280 / 3757 comments...
Processed 1290 / 3757 comments...
Processed 1300 / 3757 comments...
Processed 1310 / 3757 comments...
Processed 1320 / 3757 comments...
Processed 1330 / 3757 comments...
Processed 1340 / 3757 comments...
Processed 1350 / 3757 comments...
Processed 1360 / 3757 comments...
Processed 1370 / 3757 comments...
Processed 1380 / 3757 comments...
Processed 1390 / 3757 comments...
Processed 1400 / 3757 comments...
Processed 1410 / 3757 comments...
Processed 1420 / 3757 comments...
Processed 1430 / 3757 comments...
Processed 1440 / 3757 comments...
Processed 1450 / 3757 comments...
Processed 1460 / 3757 comments...
Processed 1470 / 3757 comments...
Processed 1480 / 3757 comments...
Processed 1490 / 3757 comments...
Processed 1500 / 3757 comments...
Processed 1510 / 3757 comments...
Processed 1520 / 3757 comments...
Processed 1530 / 3757 comments...
Processed 1540 / 3757 comments...
Processed 1550 / 3757 comments...
Processed 1560 / 3757 comments...
Processed 1570 / 3757 comments...
Processed 1580 / 3757 comments...
Processed 1590 / 3757 comments...
Processed 1600 / 3757 comments...
Processed 1610 / 3757 comments...
Processed 1620 / 3757 comments...
Processed 1630 / 3757 comments...
Processed 1640 / 3757 comments...
Processed 1650 / 3757 comments...
Processed 1660 / 3757 comments...
Processed 1670 / 3757 comments...
Processed 1680 / 3757 comments...
Processed 1690 / 3757 comments...
Processed 1700 / 3757 comments...
Processed 1710 / 3757 comments...
Processed 1720 / 3757 comments...
Processed 1730 / 3757 comments...
Processed 1740 / 3757 comments...
Processed 1750 / 3757 comments...
Processed 1760 / 3757 comments...
Processed 1770 / 3757 comments...
Processed 1780 / 3757 comments...
Processed 1790 / 3757 comments...
Processed 1800 / 3757 comments...
Processed 1810 / 3757 comments...
Processed 1820 / 3757 comments...
Processed 1830 / 3757 comments...
Processed 1840 / 3757 comments...
Processed 1850 / 3757 comments...
Processed 1860 / 3757 comments...
Processed 1870 / 3757 comments...
Processed 1880 / 3757 comments...
Processed 1890 / 3757 comments...
Processed 1900 / 3757 comments...
Processed 1910 / 3757 comments...
Processed 1920 / 3757 comments...
Processed 1930 / 3757 comments...
Processed 1940 / 3757 comments...
Processed 1950 / 3757 comments...
Processed 1960 / 3757 comments...
Processed 1970 / 3757 comments...
Processed 1980 / 3757 comments...
Processed 1990 / 3757 comments...
Processed 2000 / 3757 comments...
Processed 2010 / 3757 comments...
Processed 2020 / 3757 comments...
Processed 2030 / 3757 comments...
Processed 2040 / 3757 comments...
Processed 2050 / 3757 comments...
Processed 2060 / 3757 comments...
Processed 2070 / 3757 comments...
Processed 2080 / 3757 comments...
Processed 2090 / 3757 comments...
Processed 2100 / 3757 comments...
Processed 2110 / 3757 comments...
Processed 2120 / 3757 comments...
Processed 2130 / 3757 comments...
Processed 2140 / 3757 comments...
Processed 2150 / 3757 comments...
Processed 2160 / 3757 comments...
Processed 2170 / 3757 comments...
Processed 2180 / 3757 comments...
Processed 2190 / 3757 comments...
Processed 2200 / 3757 comments...
Processed 2210 / 3757 comments...
Processed 2220 / 3757 comments...
Processed 2230 / 3757 comments...
Processed 2240 / 3757 comments...
Processed 2250 / 3757 comments...
Processed 2260 / 3757 comments...
Processed 2270 / 3757 comments...
Processed 2280 / 3757 comments...
Processed 2290 / 3757 comments...
Processed 2300 / 3757 comments...
Processed 2310 / 3757 comments...
Processed 2320 / 3757 comments...
Processed 2330 / 3757 comments...
Processed 2340 / 3757 comments...
Processed 2350 / 3757 comments...
Processed 2360 / 3757 comments...
Processed 2370 / 3757 comments...
Processed 2380 / 3757 comments...
Processed 2390 / 3757 comments...
Processed 2400 / 3757 comments...
Processed 2410 / 3757 comments...
Processed 2420 / 3757 comments...
Processed 2430 / 3757 comments...
Processed 2440 / 3757 comments...
Processed 2450 / 3757 comments...
Processed 2460 / 3757 comments...
Processed 2470 / 3757 comments...
Processed 2480 / 3757 comments...
Processed 2490 / 3757 comments...
Processed 2500 / 3757 comments...
Processed 2510 / 3757 comments...
Processed 2520 / 3757 comments...
Processed 2530 / 3757 comments...
Processed 2540 / 3757 comments...
Processed 2550 / 3757 comments...
Processed 2560 / 3757 comments...
Processed 2570 / 3757 comments...
Processed 2580 / 3757 comments...
Processed 2590 / 3757 comments...
Processed 2600 / 3757 comments...
Processed 2610 / 3757 comments...
Processed 2620 / 3757 comments...
Processed 2630 / 3757 comments...
Processed 2640 / 3757 comments...
Processed 2650 / 3757 comments...
Processed 2660 / 3757 comments...
Processed 2670 / 3757 comments...
Processed 2680 / 3757 comments...
Processed 2690 / 3757 comments...
Processed 2700 / 3757 comments...
Processed 2710 / 3757 comments...
Processed 2720 / 3757 comments...
Processed 2730 / 3757 comments...
Processed 2740 / 3757 comments...
Processed 2750 / 3757 comments...
Processed 2760 / 3757 comments...
Processed 2770 / 3757 comments...
Processed 2780 / 3757 comments...
Processed 2790 / 3757 comments...
Processed 2800 / 3757 comments...
Processed 2810 / 3757 comments...
Processed 2820 / 3757 comments...
Processed 2830 / 3757 comments...
Processed 2840 / 3757 comments...
Processed 2850 / 3757 comments...
Processed 2860 / 3757 comments...
Processed 2870 / 3757 comments...
Processed 2880 / 3757 comments...
Processed 2890 / 3757 comments...
Processed 2900 / 3757 comments...
Processed 2910 / 3757 comments...
Processed 2920 / 3757 comments...
Processed 2930 / 3757 comments...
Processed 2940 / 3757 comments...
Processed 2950 / 3757 comments...
Processed 2960 / 3757 comments...
Processed 2970 / 3757 comments...
Processed 2980 / 3757 comments...
Processed 2990 / 3757 comments...
Processed 3000 / 3757 comments...
Processed 3010 / 3757 comments...
Processed 3020 / 3757 comments...
Processed 3030 / 3757 comments...
Processed 3040 / 3757 comments...
Processed 3050 / 3757 comments...
Processed 3060 / 3757 comments...
Processed 3070 / 3757 comments...
Processed 3080 / 3757 comments...
Processed 3090 / 3757 comments...
Processed 3100 / 3757 comments...
Processed 3110 / 3757 comments...
Processed 3120 / 3757 comments...
Processed 3130 / 3757 comments...
Processed 3140 / 3757 comments...
Processed 3150 / 3757 comments...
Processed 3160 / 3757 comments...
Processed 3170 / 3757 comments...
Processed 3180 / 3757 comments...
Processed 3190 / 3757 comments...
Processed 3200 / 3757 comments...
Processed 3210 / 3757 comments...
Processed 3220 / 3757 comments...
Processed 3230 / 3757 comments...
Processed 3240 / 3757 comments...
Processed 3250 / 3757 comments...
Processed 3260 / 3757 comments...
Processed 3270 / 3757 comments...
Processed 3280 / 3757 comments...
Processed 3290 / 3757 comments...
Processed 3300 / 3757 comments...
Processed 3310 / 3757 comments...
Processed 3320 / 3757 comments...
Processed 3330 / 3757 comments...
Processed 3340 / 3757 comments...
Processed 3350 / 3757 comments...
Processed 3360 / 3757 comments...
Processed 3370 / 3757 comments...
Processed 3380 / 3757 comments...
Processed 3390 / 3757 comments...
Processed 3400 / 3757 comments...
Processed 3410 / 3757 comments...
Processed 3420 / 3757 comments...
Processed 3430 / 3757 comments...
Processed 3440 / 3757 comments...
Processed 3450 / 3757 comments...
Processed 3460 / 3757 comments...
Processed 3470 / 3757 comments...
Processed 3480 / 3757 comments...
Processed 3490 / 3757 comments...
Processed 3500 / 3757 comments...
Processed 3510 / 3757 comments...
Processed 3520 / 3757 comments...
Processed 3530 / 3757 comments...
Processed 3540 / 3757 comments...
Processed 3550 / 3757 comments...
Processed 3560 / 3757 comments...
Processed 3570 / 3757 comments...
Processed 3580 / 3757 comments...
Processed 3590 / 3757 comments...
Processed 3600 / 3757 comments...
Processed 3610 / 3757 comments...
Processed 3620 / 3757 comments...
Processed 3630 / 3757 comments...
Processed 3640 / 3757 comments...
Processed 3650 / 3757 comments...
Processed 3660 / 3757 comments...
Processed 3670 / 3757 comments...
Processed 3680 / 3757 comments...
Processed 3690 / 3757 comments...
Processed 3700 / 3757 comments...
Processed 3710 / 3757 comments...
Processed 3720 / 3757 comments...
Processed 3730 / 3757 comments...
Processed 3740 / 3757 comments...
Processed 3750 / 3757 comments...

Done — 3757 comments processed.

,video_id,text,sentiment_label,score
0,LH_EyxsupRE,Learning tap was my secret childhood dream. I ...,POSITIVE,1.0
1,LH_EyxsupRE,Me at 3PM: I should really spend my night stud...,NEUTRAL,0.0
2,LH_EyxsupRE,Wow... i took a class and i learned more in th...,POSITIVE,1.0
3,LH_EyxsupRE,who's here to learn how to tap bc they're bore...,NEUTRAL,0.0
4,LH_EyxsupRE,Great for beginners and advanced tappers who h...,POSITIVE,1.0

In [38]:

# ── Aggregate per video ────────────────────────────────────────────────────────

def majority_label(labels):
    """Return the most frequent label, lowercased to match the existing CSV format."""
    return labels.value_counts().idxmax().lower()

agg = (
    comments_df
    .groupby("video_id")
    .agg(
        comment_sentiment               = ("sentiment_label", majority_label),
        comment_sentiment_avg_compound  = ("score", lambda x: round(x.mean(), 4)),
        comment_sentiment_comment_count = ("text", "count"),
    )
    .reset_index()
)

print(f"Aggregated sentiment for {len(agg)} videos.")
agg.head()

Aggregated sentiment for 403 videos.

,video_id,comment_sentiment,comment_sentiment_avg_compound,comment_sentiment_comment_count
0,--J5QVgWZqg,positive,0.9000,10
1,-3wwTJg6z1I,positive,0.5000,2
2,-I5CTGc93mk,positive,0.6667,3
3,-UqAnPyFK4M,positive,1.0000,10
4,-ftaSOJDRbg,positive,1.0000,10

In [39]:

# ── Merge into dance_videos.csv ────────────────────────────────────────────────
videos_df = pd.read_csv(CSV_PATH)
print(f"CSV rows before merge: {len(videos_df)}")

# Drop old sentiment columns if they already exist
drop_cols = [
    "comment_sentiment",
    "comment_sentiment_avg_compound",
    "comment_sentiment_comment_count",
]
videos_df = videos_df.drop(columns=[c for c in drop_cols if c in videos_df.columns])

merged = videos_df.merge(agg, on="video_id", how="left")

merged.to_csv(CSV_PATH, index=False, encoding="utf-8")
print(f"CSV saved  → {CSV_PATH}")
print(f"Total rows : {len(merged)} | Videos with sentiment: {agg['video_id'].nunique()}")
merged[["video_id", "comment_sentiment", "comment_sentiment_avg_compound",
        "comment_sentiment_comment_count"]].dropna().head(10)

CSV rows before merge: 527
CSV saved  → ../data/yt_data/dance_videos.csv
Total rows : 527 | Videos with sentiment: 403

,video_id,comment_sentiment,comment_sentiment_avg_compound,comment_sentiment_comment_count
0,LH_EyxsupRE,positive,0.7,20.0
1,HZruz8wO0g8,positive,0.9,10.0
2,OSa4tPmduk8,positive,0.9,10.0
3,LH_EyxsupRE,positive,0.7,20.0
4,dX7Tz_VBfK0,positive,0.8,10.0
5,B-8kxNao4aw,positive,1.0,10.0
6,QGm6v9-1ZBU,positive,0.4,10.0
7,ozagJ6DYDUA,positive,0.6,10.0
8,C9_u5Eg5ClI,positive,1.0,4.0
9,6ur6ge5fvk0,neutral,0.2,30.0