In [2]:
import  pandas as pd
from rdflib import Graph
from rdflib.plugins.sparql import prepareQuery

## Load triples into graph

In [7]:
g = Graph()

g_ontology = Graph()
g_ontology.parse('./graphs/dance_ontology.ttl', format='turtle')
# Load existing graph
g.parse('./graphs/final_kg.ttl', format='turtle')

print(f"Loaded {len(g)} triples from existing graph")

Loaded 7362 triples from existing graph

In [8]:
queries ="""
prefix dbo:   <http://dbpedia.org/ontology/>

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT (COUNT(?entity) AS ?entityCount) WHERE { ?entity rdf:type/rdfs:subClassOf* ?obj }

"""
#checks where entity is a type of something which is an subclass of another thing

query = prepareQuery(queries)
result = g.query(query)

pd.DataFrame(result.bindings)

  entityCount
0        2423

In [9]:
# SPARQL queries to type check URIs
# this prints subject predicate object relations

queries ="""
prefix dbo:   <http://dbpedia.org/ontology/>

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?s ?p ?o
WHERE {
  ?s ?p ?o .
  FILTER NOT EXISTS {
      ?s rdf:type/rdfs:subClassOf* ?domain .
      ?p rdf:type/rdfs:subPropertyOf* ?predicate .
      ?o rdf:type/rdfs:subClassOf* ?range }
  }

"""

query = prepareQuery(queries)
result = g.query(query)

pd.DataFrame(result.bindings)

,o,p,s
0,Light cardiovascular exercise,http://schema.org/name,http://example.org/dance/Light_cardiovascular_...
1,180,http://example.org/dance/minTempoBPM,http://example.org/dance/tempo_record_Latin_da...
2,0.4,http://example.org/dance/hardnessRatio,http://example.org/dance/record_Novelty_and_fa...
3,http://example.org/dance/HealthBenefit,http://www.w3.org/1999/02/22-rdf-syntax-ns#type,http://example.org/dance/Improved_core_strength
4,http://example.org/dance/EventFestival,http://www.w3.org/1999/02/22-rdf-syntax-ns#type,http://example.org/dance/Historical_balls
...,...,...,...
4535,http://www.wikidata.org/entity/Q167126,http://www.w3.org/2002/07/owl#sameAs,http://example.org/dance/Zabumba
4536,Flute,http://schema.org/name,http://example.org/dance/Flute
4537,Varies by dance style,http://schema.org/name,http://example.org/dance/Varies_by_dance_style
4538,Juan Carlos Copes,http://schema.org/name,http://example.org/dance/Juan_Carlos_Copes
4539,HARLEM SHAKE | Hip Hop Dance Workout,http://schema.org/title,http://example.org/dance/video_UW3Y1nYtg4I

# Completness - Hannes

## Find all "nan" values that were not properly filtered out

In [10]:
## check for nodes that are not defined correctly
#Find all nan values that were not properly filtered out
queries = """
PREFIX schema: <https://schema.org/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT ?s ?p ?o
WHERE {
  ?s ?p ?o .
  FILTER (str(?o) = "nan")
}
"""
query  = prepareQuery(queries)
result = g.query(query)
pd.DataFrame(result.bindings)

,o,p,s
0,nan,http://schema.org/description,http://example.org/dance/video_T9Wuh1gH7Ng
1,nan,http://schema.org/description,http://example.org/dance/video_OSa4tPmduk8
2,nan,http://schema.org/description,http://example.org/dance/video_eJPumgqw_3o
3,nan,http://schema.org/description,http://example.org/dance/video_F4kRAdr90hI

## check for nodes that are not defined correctly

In [11]:
# Not consistent and concise. Nutrition is already defined as NutritionInformation and as property, does not need to be denfined again. Also, is not complete
queries = """
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT DISTINCT ?s
WHERE {
    ?s ?p ?o .
    ?s a owl:Class .
    FILTER NOT EXISTS { ?prop rdfs:domain ?s }
    FILTER NOT EXISTS { ?prop rdfs:range ?s }
}
"""


query = prepareQuery(queries)
result = g.query(query)
pd.DataFrame(result.bindings)

Empty DataFrame
Columns: []
Index: []

# Concisness - Julio
## Intensional concisness

In [12]:
print(g.serialize(format='turtle'))

@prefix dance: <http://example.org/dance/> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix schema1: <http://schema.org/> .
@prefix skos: <http://www.w3.org/2004/02/skos/core#> .
@prefix wd: <http://www.wikidata.org/entity/> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

dance:age_Adults a dance:AgeGroup ;
    schema1:name "Adults"@en .

dance:age_All_ages a dance:AgeGroup ;
    schema1:name "All ages"@en .

dance:age_Kids a dance:AgeGroup ;
    schema1:name "Kids"@en .

dance:age_Seniors a dance:AgeGroup ;
    schema1:name "Seniors"@en .

dance:age_Teens a dance:AgeGroup ;
    schema1:name "Teens"@en .

dance:costume a owl:DatatypeProperty ;
    rdfs:label "costume"@en ;
    rdfs:domain dance:DanceRecord ;
    rdfs:range xsd:string .

dance:culturalSignificance a owl:DatatypeProperty ;
    rdfs:label "cultural significance"@en ;
    rdfs:domain dance:DanceRecord ;
    rdfs:range xsd:string .

dance:difficulty_Advanced a dance:LearningDifficulty ;
    schema1:name "Advanced"@en .

dance:difficulty_Beginner a dance:LearningDifficulty ;
    schema1:name "Beginner"@en .

dance:difficulty_Intermediate a dance:LearningDifficulty ;
    schema1:name "Intermediate"@en .

dance:formation_Circle a dance:DanceFormation ;
    schema1:name "Circle"@en .

dance:formation_Freestyle a dance:DanceFormation ;
    schema1:name "Freestyle"@en .

dance:formation_Group a dance:DanceFormation ;
    schema1:name "Group"@en .

dance:formation_Line a dance:DanceFormation ;
    schema1:name "Line"@en .

dance:formation_Mixed a dance:DanceFormation ;
    schema1:name "Mixed"@en .

dance:formation_Partner a dance:DanceFormation ;
    schema1:name "Partner"@en .

dance:formation_Processional a dance:DanceFormation ;
    schema1:name "Processional"@en .

dance:formation_Solo a dance:DanceFormation ;
    schema1:name "Solo"@en .

dance:formation_Square a dance:DanceFormation ;
    schema1:name "Square"@en .

dance:hardnessRatio a owl:DatatypeProperty ;
    rdfs:label "hardness ratio"@en ;
    rdfs:domain dance:DanceRecord ;
    rdfs:range xsd:decimal .

dance:hasAgeGroup a owl:ObjectProperty ;
    rdfs:label "has age group"@en ;
    rdfs:domain dance:DanceRecord ;
    rdfs:range dance:AgeGroup .

dance:hasAssociatedMusicGenre a owl:ObjectProperty ;
    rdfs:label "has associated music genre"@en ;
    rdfs:domain dance:DanceRecord ;
    rdfs:range dance:MusicGenre .

dance:hasDanceFormation a owl:ObjectProperty ;
    rdfs:label "has dance formation"@en ;
    rdfs:domain dance:DanceRecord ;
    rdfs:range dance:DanceFormation .

dance:hasDanceStyle a owl:ObjectProperty ;
    rdfs:label "has dance style"@en ;
    rdfs:domain dance:DanceRecord ;
    rdfs:range dance:DanceStyle .

dance:hasDanceType a owl:ObjectProperty ;
    rdfs:label "has dance type"@en ;
    rdfs:domain dance:DanceRecord ;
    rdfs:range dance:DanceType .

dance:hasEventFestival a owl:ObjectProperty ;
    rdfs:label "has event and festival"@en ;
    rdfs:domain dance:DanceRecord ;
    rdfs:range dance:EventFestival .

dance:hasFamousPractitioner a owl:ObjectProperty ;
    rdfs:label "has famous practitioner"@en ;
    rdfs:domain dance:DanceRecord ;
    rdfs:range dance:Practitioner .

dance:hasHealthBenefit a owl:ObjectProperty ;
    rdfs:label "has health benefit"@en ;
    rdfs:domain dance:DanceRecord ;
    rdfs:range dance:HealthBenefit .

dance:hasInstrument a owl:ObjectProperty ;
    rdfs:label "has instrument"@en ;
    rdfs:domain dance:DanceRecord ;
    rdfs:range dance:Instrument .

dance:hasLearningDifficulty a owl:ObjectProperty ;
    rdfs:label "has learning difficulty"@en ;
    rdfs:domain dance:DanceRecord ;
    rdfs:range dance:LearningDifficulty .

dance:hasOrigin a owl:ObjectProperty ;
    rdfs:label "has origin"@en ;
    rdfs:domain dance:DanceRecord ;
    rdfs:range dance:Origin .

dance:hasTempoRange a owl:ObjectProperty ;
    rdfs:label "has tempo range"@en ;
    rdfs:domain dance:DanceRecord ;
    rdfs:range dance:TempoRange .

dance:hasTimePeriod a owl:ObjectProperty ;
    rdfs:label "has time period"@en ;
    rdfs:domain dance:DanceRecord ;
    rdfs:range dance:TimePeriod .

dance:hasYTLink a owl:ObjectProperty ;
    rdfs:label "has yt link"@en ;
    rdfs:domain dance:DanceStyle ;
    rdfs:range dance:YTLINK .

dance:maxTempoBPM a owl:DatatypeProperty ;
    rdfs:label "max tempo bpm"@en ;
    rdfs:domain dance:TempoRange ;
    rdfs:range xsd:integer .

dance:minTempoBPM a owl:DatatypeProperty ;
    rdfs:label "min tempo bpm"@en ;
    rdfs:domain dance:TempoRange ;
    rdfs:range xsd:integer .

dance:modernAdaptations a owl:DatatypeProperty ;
    rdfs:label "modern adaptations"@en ;
    rdfs:domain dance:DanceRecord ;
    rdfs:range xsd:string .

dance:notableCharacteristics a owl:DatatypeProperty ;
    rdfs:label "notable characteristics"@en ;
    rdfs:domain dance:DanceRecord ;
    rdfs:range xsd:string .

dance:record_American_Jazz_dance a dance:DanceRecord ;
    dance:costume "Flexible, form-fitting attire to allow freedom of movement, often with jazz shoes."@en ;
    dance:culturalSignificance "Jazz dance evolved alongside jazz music as a form of social and theatrical dance, reflecting African American cultural expression and innovation."@en ;
    dance:hardnessRatio 0.5 ;
    dance:hasAgeGroup dance:All_ages ;
    dance:hasAssociatedMusicGenre dance:Blues,
        dance:Jazz ;
    dance:hasDanceFormation dance:Solo ;
    dance:hasDanceStyle dance:Jazz_dance ;
    dance:hasDanceType dance:American ;
    dance:hasEventFestival dance:Jazz_festivals,
        dance:Theater_productions ;
    dance:hasFamousPractitioner dance:Bob_Fosse,
        dance:Katherine_Dunham ;
    dance:hasHealthBenefit dance:Cardiovascular_fitness,
        dance:Enhanced_coordination,
        dance:Enhanced_flexibility ;
    dance:hasInstrument dance:Body_percussion,
        dance:Piano,
        dance:Saxophone,
        dance:Trumpet ;
    dance:hasLearningDifficulty dance:Intermediate ;
    dance:hasOrigin dance:United_States ;
    dance:hasTempoRange dance:tempo_record_American_Jazz_dance ;
    dance:hasTimePeriod dance:Early_20th_century ;
    dance:modernAdaptations "Incorporated into musical theater and contemporary dance training worldwide."@en ;
    dance:notableCharacteristics "Energetic, rhythmic movements with improvisation, isolations, and syncopation. Often performed with sharp, dynamic gestures."@en ;
    schema1:name "American - Jazz dance"@en .

dance:record_American_Moonwalk_\(Michael_Jackson_style\) a dance:DanceRecord ;
    dance:costume "Often performed with sequined gloves, fedora hats, and loafers to enhance visual effect."@en ;
    dance:culturalSignificance "Popularized by Michael Jackson, the moonwalk became an iconic dance move symbolizing smoothness and illusion in pop culture worldwide."@en ;
    dance:hardnessRatio 0.8 ;
    dance:hasAgeGroup dance:Teens ;
    dance:hasAssociatedMusicGenre dance:Funk,
        dance:Pop,
        <http://example.org/dance/R&B> ;
    dance:hasDanceFormation dance:Solo ;
    dance:hasDanceStyle dance:Moonwalk_\(Michael_Jackson_style\) ;
    dance:hasDanceType dance:American ;
    dance:hasEventFestival dance:Dance_competitions,
        dance:Pop_concerts ;
    dance:hasFamousPractitioner dance:Michael_Jackson ;
    dance:hasHealthBenefit dance:Balance_improvement,
        dance:Enhanced_coordination,
        dance:Lower_body_strength ;
    dance:hasInstrument dance:Pop_music_backing_tracks ;
    dance:hasLearningDifficulty dance:Advanced ;
    dance:hasOrigin dance:United_States ;
    dance:hasTempoRange dance:tempo_record_American_Moonwalk_\(Michael_Jackson_style\) ;
    dance:hasTimePeriod dance:1980s ;
    dance:modernAdaptations "Used in hip-hop and street dance performances as a signature move."@en ;
    dance:notableCharacteristics "A gliding backward motion that creates the illusion of walking forward. Requires precise foot control and balance."@en ;
    schema1:name "American - Moonwalk (Michael Jackson style)"@en .

dance:record_American_Stepping a dance:DanceRecord ;
    dance:costume "Often performed in fraternity/sorority apparel or coordinated outfits representing group identity."@en ;
    dance:culturalSignificance "Stepping is a percussive dance form developed in African American fraternities and sororities as a form of group expression and unity. It carries strong cultural and social significance within these communities."@en ;
    dance:hardnessRatio 0.7 ;
    dance:hasAgeGroup dance:Teens ;
    dance:hasAssociatedMusicGenre dance:Hip-hop,
        dance:Percussive ;
    dance:hasDanceFormation dance:Group ;
    dance:hasDanceStyle dance:Stepping ;
    dance:hasDanceType dance:American ;
    dance:hasEventFestival dance:Cultural_festivals,
        dance:Greek_life_events,
        dance:Step_shows ;
    dance:hasFamousPractitioner dance:Traditional_dancers ;
    dance:hasHealthBenefit dance:Cardiovascular_fitness,
        dance:Enhanced_coordination,
        dance:Muscle_toning ;
    dance:hasInstrument dance:Body_percussion ;
    dance:hasLearningDifficulty dance:Intermediate ;
    dance:hasOrigin dance:United_States ;
    dance:hasTempoRange dance:tempo_record_American_Stepping ;
    dance:hasTimePeriod dance:19th_century ;
    dance:modernAdaptations "Stepping has influenced hip-hop choreography and is used in community empowerment programs."@en ;
    dance:notableCharacteristics "Uses the body as an instrument through clapping, stomping, and vocalizations. Highly synchronized group formations and call-and-response patterns."@en ;
    schema1:name "American - Stepping"@en .

dance:record_American_Tap_dancing a dance:DanceRecord ;
    dance:costume "Dress shoes with metal taps, often paired with formal or theatrical attire."@en ;
    dance:culturalSignificance "Tap dancing emerged as a unique American art form blending African tribal dances and European clog dancing. It became a popular theatrical and entertainment dance style in vaudeville and Broadway."@en ;
    dance:hardnessRatio 0.6 ;
    dance:hasAgeGroup dance:All_ages ;
    dance:hasAssociatedMusicGenre dance:Jazz,
        dance:Swing ;
    dance:hasDanceFormation dance:Solo ;
    dance:hasDanceStyle dance:Tap_dancing ;
    dance:hasDanceType dance:American ;
    dance:hasEventFestival dance:American_Tap_Festival,
        dance:Tap_Dance_Day ;
    dance:hasFamousPractitioner dance:Fred_Astaire,
        dance:Gregory_Hines,
        dance:Savion_Glover ;
    dance:hasHealthBenefit dance:Enhanced_teamwork,
        dance:Improved_cardiovascular_health,
        dance:Stress_reduction ;
    dance:hasInstrument dance:Body_percussion,
        dance:Double_bass,
        dance:Piano,
        dance:Saxophone ;
    dance:hasLearningDifficulty dance:Intermediate ;
    dance:hasOrigin dance:United_States ;
    dance:hasTempoRange dance:tempo_record_American_Tap_dancing ;
    dance:hasTimePeriod dance:19th_century ;
    dance:modernAdaptations "Modern tap incorporates elements of hip-hop and contemporary dance styles, expanding its musical range."@en ;
    dance:notableCharacteristics "Rhythmic footwork with metal taps on shoes creates complex percussive sounds. Emphasis on improvisation and syncopation."@en ;
    schema1:name "American - Tap dancing"@en .

dance:record_Belly_dance_American_Tribal_Style a dance:DanceRecord ;
    dance:costume "Coordinated ethnic-inspired costumes with layered skirts, coin belts, and tribal jewelry."@en ;
    dance:culturalSignificance "American Tribal Style (ATS) is a modern group improvisational belly dance form developed in the U.S., emphasizing community and collective creativity."@en ;
    dance:hardnessRatio 0.7 ;
    dance:hasAgeGroup dance:Adults ;
    dance:hasAssociatedMusicGenre dance:Middle_Eastern,
        dance:World_fusion ;
    dance:hasDanceFormation dance:Group ;
    dance:hasDanceStyle dance:American_Tribal_Style ;
    dance:hasDanceType dance:Belly_dance ;
    dance:hasEventFestival dance:Community_workshops,
        dance:Tribal_dance_festivals ;
    dance:hasFamousPractitioner dance:FatChanceBellyDance_troupe ;
    dance:hasHealthBenefit dance:Community_bonding,
        dance:Enhanced_teamwork,
        dance:Improved_leg_strength ;
    dance:hasInstrument dance:Cymbals,
        dance:Darbuka,
        dance:Frame_drum ;
    dance:hasLearningDifficulty dance:Intermediate ;
    dance:hasOrigin dance:United_States ;
    dance:hasTempoRange dance:tempo_record_Belly_dance_American_Tribal_Style ;
    dance:hasTimePeriod dance:Late_20th_century ;
    dance:modernAdaptations "Widely taught and performed in global ATS communities, fostering cultural exchange."@en ;
    dance:notableCharacteristics "Group improvisation with a vocabulary of shared movements and cues. Strong, grounded postures and coordinated formations."@en ;
    schema1:name "Belly dance - American Tribal Style"@en .

dance:record_Belly_dance_Baladi a dance:DanceRecord ;
    dance:costume "Traditional long skirts with embroidered tops and hip scarves adorned with coins."@en ;
    dance:culturalSignificance "Baladi is a popular Egyptian folk dance symbolizing rural life and cultural identity, often performed at social gatherings and celebrations."@en ;
    dance:hardnessRatio 0.6 ;
    dance:hasAgeGroup dance:Adults ;
    dance:hasAssociatedMusicGenre dance:Arabic_folk,
        dance:Baladi_music ;
    dance:hasDanceFormation dance:Solo ;
    dance:hasDanceStyle dance:Baladi ;
    dance:hasDanceType dance:Belly_dance ;
    dance:hasEventFestival dance:Family_celebrations,
        dance:Local_festivals ;
    dance:hasFamousPractitioner dance:Professional_ballroom_dancers ;
    dance:hasHealthBenefit dance:Cardiovascular_fitness,
        dance:Enhanced_flexibility,
        dance:Improved_leg_strength ;
    dance:hasInstrument dance:Accordion,
        dance:Darbuka,
        dance:Oud,
        dance:Riq,
        dance:Voice ;
    dance:hasLearningDifficulty dance:Intermediate ;
    dance:hasOrigin dance:Egypt ;
    dance:hasTempoRange dance:tempo_record_Belly_dance_Baladi ;
    dance:hasTimePeriod dance:Early_20th_century ;
    dance:modernAdaptations "Baladi is incorporated into modern belly dance performances and fusion styles globally."@en ;
    dance:notableCharacteristics "It features grounded movements, hip circles, and expressive arm gestures, emphasizing connection to the earth and community."@en ;
    schema1:name "Belly dance - Baladi"@en .

dance:record_Belly_dance_Kawleeya a dance:DanceRecord ;
    dance:costume "Colorful skirts and fitted tops with coin belts to accentuate hip movements."@en ;
    dance:culturalSignificance "Kawleeya is a traditional Egyptian folk dance performed mainly by women, often at celebrations and social gatherings, symbolizing joy and community bonding."@en ;
    dance:hardnessRatio 0.5 ;
    dance:hasAgeGroup dance:Adults ;
    dance:hasAssociatedMusicGenre dance:Arabic_folk,
        dance:Traditional_Egyptian ;
    dance:hasDanceFormation dance:Group ;
    dance:hasDanceStyle dance:Kawleeya ;
    dance:hasDanceType dance:Belly_dance ;
    dance:hasEventFestival dance:Community_celebrations,
        dance:Local_weddings ;
    dance:hasFamousPractitioner dance:Traditional_Kawleeya_dancers ;
    dance:hasHealthBenefit dance:Cardiovascular_endurance,
        dance:Enhanced_flexibility,
        dance:Improved_leg_strength ;
    dance:hasInstrument dance:Accordion,
        dance:Darbuka,
        dance:Oud,
        dance:Riq,
        dance:Voice ;
    dance:hasLearningDifficulty dance:Intermediate ;
    dance:hasOrigin dance:Egypt ;
    dance:hasTempoRange dance:tempo_record_Belly_dance_Kawleeya ;
    dance:hasTimePeriod dance:19th_century ;
    dance:modernAdaptations "Kawleeya has influenced contemporary belly dance performances worldwide, often incorporated into fusion styles."@en ;
    dance:notableCharacteristics "It features rhythmic hip movements, shimmies, and fluid arm gestures, often performed with a lively and playful attitude."@en ;
    schema1:name "Belly dance - Kawleeya"@en .

dance:record_Belly_dance_Khaleeji a dance:DanceRecord ;
    dance:costume "Flowing dresses with long sleeves and ornate headpieces reflecting Gulf culture."@en ;
    dance:culturalSignificance "Khaleeji dance is a traditional dance from the Gulf region, often performed at weddings and cultural festivals to celebrate heritage and social unity."@en ;
    dance:hardnessRatio 0.4 ;
    dance:hasAgeGroup dance:Adults ;
    dance:hasAssociatedMusicGenre dance:Arabic_folk,
        dance:Khaleeji_music ;
    dance:hasDanceFormation dance:Solo ;
    dance:hasDanceStyle dance:Khaleeji ;
    dance:hasDanceType dance:Belly_dance ;
    dance:hasEventFestival dance:Gulf_cultural_festivals,
        dance:Wedding_ceremonies ;
    dance:hasFamousPractitioner dance:Professional_ballroom_dancers ;
    dance:hasHealthBenefit dance:Enhanced_coordination,
        dance:Improved_posture,
        dance:Stress_reduction ;
    dance:hasInstrument dance:Daff,
        dance:Ney,
        dance:Oud,
        dance:Tabla,
        dance:Voice ;
    dance:hasLearningDifficulty dance:Beginner ;
    dance:hasOrigin dance:Arabian_Peninsula ;
    dance:hasTempoRange dance:tempo_record_Belly_dance_Khaleeji ;
    dance:hasTimePeriod dance:19th_century ;
    dance:modernAdaptations "Modern Khaleeji incorporates contemporary music elements while preserving traditional movements."@en ;
    dance:notableCharacteristics "Characterized by slow, graceful movements of the hair and hands, with subtle hip sways and rhythmic footwork."@en ;
    schema1:name "Belly dance - Khaleeji"@en .

dance:record_Belly_dance_Oriental_fusion a dance:DanceRecord ;
    dance:costume "Eclectic costumes mixing traditional and modern elements, often customized by dancers."@en ;
    dance:culturalSignificance "Oriental fusion blends traditional belly dance with contemporary and global dance styles, reflecting cultural exchange and innovation."@en ;
    dance:hardnessRatio 0.7 ;
    dance:hasAgeGroup dance:Adults ;
    dance:hasAssociatedMusicGenre dance:Electronic,
        dance:Middle_Eastern,
        dance:World_fusion ;
    dance:hasDanceFormation dance:Solo ;
    dance:hasDanceStyle dance:Oriental_fusion ;
    dance:hasDanceType dance:Belly_dance ;
    dance:hasEventFestival dance:Fusion_dance_workshops,
        dance:International_dance_festivals ;
    dance:hasFamousPractitioner dance:Contemporary_dance_artists ;
    dance:hasHealthBenefit dance:Creative_expression,
        dance:Enhanced_flexibility,
        dance:Improved_leg_strength ;
    dance:hasInstrument dance:Darbuka,
        dance:Electronic_synthesizer,
        dance:Oud,
        dance:Voice ;
    dance:hasLearningDifficulty dance:Advanced ;
    dance:hasOrigin dance:Middle_East ;
    dance:hasTempoRange dance:tempo_record_Belly_dance_Oriental_fusion ;
    dance:hasTimePeriod dance:Late_20th_century ;
    dance:modernAdaptations "Widely used in global belly dance communities and stage performances."@en ;
    dance:notableCharacteristics "Combines classical belly dance moves with elements from ballet, hip-hop, and modern dance. Emphasizes creativity and personal expression."@en ;
    schema1:name "Belly dance - Oriental fusion"@en .

dance:record_Belly_dance_Raqs_Sharqi a dance:DanceRecord ;
    dance:costume "Typically a fitted beaded bra and belt set with a flowing skirt or harem pants."@en ;
    dance:culturalSignificance "Raqs Sharqi is the classical Egyptian style of belly dance performed in theaters and social events, embodying traditional Middle Eastern aesthetics and storytelling."@en ;
    dance:hardnessRatio 0.6 ;
    dance:hasAgeGroup dance:Adults ;
    dance:hasAssociatedMusicGenre dance:Arabic_folk,
        dance:Middle_Eastern ;
    dance:hasDanceFormation dance:Solo ;
    dance:hasDanceStyle dance:Raqs_Sharqi ;
    dance:hasDanceType dance:Belly_dance ;
    dance:hasEventFestival dance:Cairo_International_Belly_Dance_Festival,

- Some recipes are declared as products: <http://kg-course/food-nutrition/recipe/38> a schema:Product ;
- Two classes for nutrition: Nutrition - NutritionInformation (from the ontology graph)

## Extensional concisness

In [14]:
# Concisness of data - check for duplicate recipes by name
q1 = """
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX dance: <http://example.org/dance/>

SELECT ?recipeName (COUNT(?recipe) AS ?duplicateCount) (GROUP_CONCAT(STRAFTER(STR(?recipe), "dance/"); separator=", ") AS ?recipeIDs)
WHERE {
    ?recipe a dance:DanceRecord ;
            schema:name ?recipeName .
}
GROUP BY ?recipeName
HAVING (COUNT(?recipe) > 1)
ORDER BY DESC(?duplicateCount)
"""
query  = prepareQuery(q1)
result = g.query(query)
pd.DataFrame(result.bindings)

Empty DataFrame
Columns: []
Index: []

In [22]:
# Concisness of data - different instructions for the same recipe
q2 = """
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX dance: <http://example.org/dance/>


SELECT ?recipe1 ?recipe2 ?recipeName
WHERE {
    ?recipe1 a dance:DanceRecord ;
             schema:name ?recipeName ;
             schema:uploadDate ?instruction .
             
    ?recipe2 a dance:DanceRecord ;
             schema:name ?recipeName ;
             schema:uploadDate ?instruction .
             
    FILTER (?recipe1 != ?recipe2)
    FILTER (STR(?recipe1) < STR(?recipe2)) 
}
"""
query  = prepareQuery(q2)
result = g.query(query)
pd.DataFrame(result.bindings)

Empty DataFrame
Columns: []
Index: []

In [10]:
# Concisness of data - multiple values for the same nutrition property 

#TODO: Change this to dance data
q3 = """
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT ?nutritionNode ?property (COUNT(?value) AS ?valueCount)
WHERE {
    ?nutritionNode ?property ?value .
    
    FILTER(?property IN (schema:calories, schema:carbohydrateContent, schema:fatContent, schema:proteinContent))
}
GROUP BY ?nutritionNode ?property
HAVING (COUNT(?value) > 1)
ORDER BY DESC(?valueCount)
"""
query  = prepareQuery(q3)
result = g.query(query)
pd.DataFrame(result.bindings)

,nutritionNode,property,valueCount
0,http://kg-course/food-nutrition/recipe/48/nutr...,https://schema.org/calories,6
1,http://kg-course/food-nutrition/recipe/48/nutr...,https://schema.org/fatContent,6
2,http://kg-course/food-nutrition/recipe/48/nutr...,https://schema.org/carbohydrateContent,6
3,http://kg-course/food-nutrition/recipe/48/nutr...,https://schema.org/proteinContent,6
4,http://kg-course/food-nutrition/recipe/42/nutr...,https://schema.org/fatContent,4
5,http://kg-course/food-nutrition/recipe/42/nutr...,https://schema.org/proteinContent,4
6,http://kg-course/food-nutrition/recipe/42/nutr...,https://schema.org/calories,4
7,http://kg-course/food-nutrition/recipe/42/nutr...,https://schema.org/carbohydrateContent,4

# Consistency - Hannes


## find triples where a property is used on a subject whose type does not match the propertys declared domain

In [18]:
queries = """
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT DISTINCT ?s ?p ?o ?expectedDomain ?actualType
WHERE {
  ?p rdfs:domain ?expectedDomain .
  ?s ?p ?o .
  ?s rdf:type ?actualType .
  FILTER (?actualType != ?expectedDomain)
  FILTER NOT EXISTS {
    ?actualType rdfs:subClassOf* ?expectedDomain .
  }
}
ORDER BY ?p
"""
query  = prepareQuery(queries)
result = g.query(query)
pd.DataFrame(result.bindings)

,actualType,expectedDomain,o,p,s
0,http://example.org/dance/MusicGenre,http://example.org/dance/DanceStyle,http://example.org/dance/video_8n29Pc4Ik4s,http://example.org/dance/hasYTLink,http://example.org/dance/Bachata
1,http://example.org/dance/MusicGenre,http://example.org/dance/DanceStyle,http://example.org/dance/video_gtQOIc_mp-0,http://example.org/dance/hasYTLink,http://example.org/dance/Bolero
2,http://example.org/dance/MusicGenre,http://example.org/dance/DanceStyle,http://example.org/dance/video_3XBJevNfZMg,http://example.org/dance/hasYTLink,http://example.org/dance/Cha_Cha
3,http://example.org/dance/MusicGenre,http://example.org/dance/DanceStyle,http://example.org/dance/video_3UXtxn8B2OU,http://example.org/dance/hasYTLink,http://example.org/dance/Duranguense
4,http://example.org/dance/MusicGenre,http://example.org/dance/DanceStyle,http://example.org/dance/video_vudZL4_uqLo,http://example.org/dance/hasYTLink,http://example.org/dance/Forró
5,http://example.org/dance/MusicGenre,http://example.org/dance/DanceStyle,http://example.org/dance/video_8nhqnxirY9o,http://example.org/dance/hasYTLink,http://example.org/dance/Lambada
6,http://example.org/dance/MusicGenre,http://example.org/dance/DanceStyle,http://example.org/dance/video_daaHi0jtHlw,http://example.org/dance/hasYTLink,http://example.org/dance/Merengue
7,http://example.org/dance/MusicGenre,http://example.org/dance/DanceStyle,http://example.org/dance/video_-UqAnPyFK4M,http://example.org/dance/hasYTLink,http://example.org/dance/Milonga
8,http://example.org/dance/MusicGenre,http://example.org/dance/DanceStyle,http://example.org/dance/video_rrdKszMyWQk,http://example.org/dance/hasYTLink,http://example.org/dance/Pasodoble
9,http://example.org/dance/MusicGenre,http://example.org/dance/DanceStyle,http://example.org/dance/video_qbPzvHAGvm4,http://example.org/dance/hasYTLink,http://example.org/dance/Zouk
10,http://example.org/dance/MusicGenre,http://example.org/dance/DanceStyle,http://example.org/dance/video_l5SjNK-Gi_4,http://example.org/dance/hasYTLink,http://example.org/dance/Cumbia
11,http://example.org/dance/MusicGenre,http://example.org/dance/DanceStyle,http://example.org/dance/video__0j8TObZbbE,http://example.org/dance/hasYTLink,http://example.org/dance/Flamenco
12,http://example.org/dance/MusicGenre,http://example.org/dance/DanceStyle,http://example.org/dance/video_4JcLQG6-FN0,http://example.org/dance/hasYTLink,http://example.org/dance/Mambo
13,http://example.org/dance/MusicGenre,http://example.org/dance/DanceStyle,http://example.org/dance/video_YbZV7VJ1oCE,http://example.org/dance/hasYTLink,http://example.org/dance/Rock_and_Roll


## Find ObjectProperties used with literal values instead of URIs, similar to how its done in completness check

In [19]:

# found that object Property is
queries = """
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT DISTINCT ?objProp
WHERE {
  ?objProp a owl:ObjectProperty
}
"""
query  = prepareQuery(queries)
result = g.query(query)
pd.DataFrame(result.bindings)

                                             objProp
0               http://example.org/dance/hasAgeGroup
1   http://example.org/dance/hasAssociatedMusicGenre
2         http://example.org/dance/hasDanceFormation
3             http://example.org/dance/hasDanceStyle
4              http://example.org/dance/hasDanceType
5          http://example.org/dance/hasEventFestival
6     http://example.org/dance/hasFamousPractitioner
7          http://example.org/dance/hasHealthBenefit
8             http://example.org/dance/hasInstrument
9     http://example.org/dance/hasLearningDifficulty
10                http://example.org/dance/hasOrigin
11            http://example.org/dance/hasTempoRange
12            http://example.org/dance/hasTimePeriod
13                http://example.org/dance/hasYTLink

In [20]:
queries = """
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT DISTINCT ?subject ?property ?object
WHERE {
  ?property a owl:ObjectProperty .
  ?subject ?property ?object .
  FILTER (isLiteral(?object))
}
"""
query  = prepareQuery(queries)
result = g.query(query)
pd.DataFrame(result.bindings)

Empty DataFrame
Columns: []
Index: []


## entities of type schema:Recipe that are missing key expected properties (schema:name, schema:nutrition, schema:recipeIngredient)

In [21]:
#TODO: Finish this

queries = """
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX schema: <https://schema.org/>

SELECT DISTINCT ?recipe ?missingProperty
WHERE {
  ?recipe rdf:type schema:Recipe .
  VALUES ?missingProperty { schema:name schema:nutrition schema:recipeIngredient schema:recipeInstructions }
  FILTER NOT EXISTS { ?recipe ?missingProperty ?any }
}
ORDER BY ?recipe ?missingProperty
"""
query  = prepareQuery(queries)
result = g.query(query)
pd.DataFrame(result.bindings)

Empty DataFrame
Columns: []
Index: []

# Syntactic Validity - Hannes

## Find all literal Type mismatches (except for langString and String which are passable (I think))

In [25]:

## all cases where the literalType is not the same as the range

queries = """
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX schema: <https://schema.org/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX dbr: <http://dbpedia.org/resource/>

SELECT DISTINCT ?s ?literal ?range ?literalType
WHERE {
  ?s ?p ?literal .
  ?p rdfs:range ?range .
  FILTER (isLiteral(?literal) && ?p != rdfs:label)

  BIND (datatype(?literal) AS ?literalType)
  FILTER (?range != ?literalType)
  FILTER (!(?range = xsd:string && ?literalType = rdf:langString))
  FILTER (!(?range = rdf:langString && ?literalType = xsd:string))
}
"""
query  = prepareQuery(queries)
result = g.query(query)

pd.DataFrame(result.bindings)

,literal,literalType,range,s
0,PT6M3S,http://www.w3.org/2001/XMLSchema#string,http://www.w3.org/2001/XMLSchema#duration,http://example.org/dance/video_-IdY7BQTCWs
1,PT7M3S,http://www.w3.org/2001/XMLSchema#string,http://www.w3.org/2001/XMLSchema#duration,http://example.org/dance/video_-JCJUaoRPLI
2,PT6M52S,http://www.w3.org/2001/XMLSchema#string,http://www.w3.org/2001/XMLSchema#duration,http://example.org/dance/video_-UqAnPyFK4M
3,PT7M47S,http://www.w3.org/2001/XMLSchema#string,http://www.w3.org/2001/XMLSchema#duration,http://example.org/dance/video_1X8v6rbe27s
4,PT19M34S,http://www.w3.org/2001/XMLSchema#string,http://www.w3.org/2001/XMLSchema#duration,http://example.org/dance/video_1ijkYKoig1o
...,...,...,...,...
119,PT15M45S,http://www.w3.org/2001/XMLSchema#string,http://www.w3.org/2001/XMLSchema#duration,http://example.org/dance/video_wucZxx-XaVA
120,PT4M4S,http://www.w3.org/2001/XMLSchema#string,http://www.w3.org/2001/XMLSchema#duration,http://example.org/dance/video_y-txQrkv1bE
121,PT8M8S,http://www.w3.org/2001/XMLSchema#string,http://www.w3.org/2001/XMLSchema#duration,http://example.org/dance/video_y7_cQiktu7Y
122,PT4M20S,http://www.w3.org/2001/XMLSchema#string,http://www.w3.org/2001/XMLSchema#duration,http://example.org/dance/video_yKx5AW7doqw
123,PT7M57S,http://www.w3.org/2001/XMLSchema#string,http://www.w3.org/2001/XMLSchema#duration,http://example.org/dance/video_zTquuJnJBnY

## numbers stored as strings

In [26]:
queries = """
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT ?s ?p ?o
WHERE {
  ?s ?p ?o .
  ?p rdfs:range ?range .
  FILTER (?range IN (xsd:double, xsd:integer, xsd:float, xsd:decimal))
  FILTER (datatype(?o) = xsd:string)
}
ORDER BY ?p
"""
query  = prepareQuery(queries)
result = g.query(query)
pd.DataFrame(result.bindings)

Empty DataFrame
Columns: []
Index: []

## string literals without a language

In [27]:
queries = """
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT ?s ?p ?o
WHERE {
  ?s ?p ?o .
  FILTER (isLiteral(?o))
  FILTER (datatype(?o) = xsd:string)
}
ORDER BY ?p
"""
query  = prepareQuery(queries)
result = g.query(query)
pd.DataFrame(result.bindings)

,o,p,s
0,Madonna - Vogue Choreographed by Dean Lee Twit...,http://schema.org/description,http://example.org/dance/video_nQcYWBrV10U
1,Let Dancing with The Stars Pro Dancer Brian Fo...,http://schema.org/description,http://example.org/dance/video_3XBJevNfZMg
2,This tutorial video is specifically designed t...,http://schema.org/description,http://example.org/dance/video_1X8v6rbe27s
3,"Центр трайбл-культуры в Санкт-Петербурге, колл...",http://schema.org/description,http://example.org/dance/video_MFZG49yVtco
4,Learn how to dance a crazy good Jive Basic wit...,http://schema.org/description,http://example.org/dance/video_KGYQK-8WUPI
...,...,...,...
486,positive,http://www.wikidata.org/entity/Q28659447,http://example.org/dance/video_HZruz8wO0g8
487,positive,http://www.wikidata.org/entity/Q28659447,http://example.org/dance/video_Thnvgf_3aoQ
488,positive,http://www.wikidata.org/entity/Q28659447,http://example.org/dance/video_BzrA38NiyoA
489,positive,http://www.wikidata.org/entity/Q28659447,http://example.org/dance/video_yKx5AW7doqw
490,positive,http://www.wikidata.org/entity/Q28659447,http://example.org/dance/video_IKcp8ibER-s

# Semantic Accuracy - Mikolaj

## hardnessRatio must be between 0.0 and 1.0

In [40]:
queries = """
PREFIX dance: <http://example.org/dance/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?record ?ratio
WHERE {
  ?record a dance:DanceRecord ;
          dance:hardnessRatio ?ratio .
  FILTER (?ratio < 0.0 || ?ratio > 1.0)
}
ORDER BY ?ratio
"""
query  = prepareQuery(queries)
result = g.query(query)
pd.DataFrame(result.bindings)

Empty DataFrame
Columns: []
Index: []

## 2. minTempoBPM must be strictly less than maxTempoBPM

In [42]:
queries = """
PREFIX dance: <http://example.org/dance/>

SELECT ?tempoRange ?min ?max
WHERE {
  ?tempoRange a dance:TempoRange ;
              dance:minTempoBPM ?min ;
              dance:maxTempoBPM ?max .
  FILTER (?min >= ?max)
}
ORDER BY ?tempoRange
"""
query  = prepareQuery(queries)
result = g.query(query)
pd.DataFrame(result.bindings)

Empty DataFrame
Columns: []
Index: []

## Each DanceRecord must link to exactly one DanceStyle

In [41]:
queries = """
PREFIX dance: <http://example.org/dance/>

SELECT ?record (COUNT(?style) AS ?styleCount)
WHERE {
  ?record a dance:DanceRecord .
  OPTIONAL { ?record dance:hasDanceStyle ?style }
}
GROUP BY ?record
HAVING (COUNT(?style) != 1)
ORDER BY ?styleCount
"""
query  = prepareQuery(queries)
result = g.query(query)
pd.DataFrame(result.bindings)

DanceRecords without exactly one DanceStyle: 0

Empty DataFrame
Columns: []
Index: []

## Each DanceRecord must link to exactly one DanceType

In [43]:
queries = """
PREFIX dance: <http://example.org/dance/>

SELECT ?record (COUNT(?danceType) AS ?typeCount)
WHERE {
  ?record a dance:DanceRecord .
  OPTIONAL { ?record dance:hasDanceType ?danceType }
}
GROUP BY ?record
HAVING (COUNT(?danceType) != 1)
ORDER BY ?typeCount
"""
query  = prepareQuery(queries)
result = g.query(query)
pd.DataFrame(result.bindings)

DanceRecords without exactly one DanceType: 0

Empty DataFrame
Columns: []
Index: []

## Each DanceRecord must link to exactly one LearningDifficulty

In [44]:
queries = """
PREFIX dance: <http://example.org/dance/>

SELECT ?record (COUNT(?diff) AS ?diffCount)
WHERE {
  ?record a dance:DanceRecord .
  OPTIONAL { ?record dance:hasLearningDifficulty ?diff }
}
GROUP BY ?record
HAVING (COUNT(?diff) != 1)
ORDER BY ?diffCount
"""
query  = prepareQuery(queries)
result = g.query(query)
pd.DataFrame(result.bindings)

Empty DataFrame
Columns: []
Index: []

## LearningDifficulty values must only be Beginner, Intermediate or Advanced

In [45]:
queries = """
PREFIX dance: <http://example.org/dance/>
PREFIX schema1: <http://schema.org/>

SELECT DISTINCT ?record ?diffLabel
WHERE {
  ?record a dance:DanceRecord ;
          dance:hasLearningDifficulty ?diff .
  ?diff schema1:name ?diffLabel .
  FILTER (?diffLabel NOT IN ("Beginner"@en, "Intermediate"@en, "Advanced"@en))
}
"""
query  = prepareQuery(queries)
result = g.query(query)
pd.DataFrame(result.bindings)

Empty DataFrame
Columns: []
Index: []

## Each DanceRecord must link to exactly one AgeGroup

In [46]:
queries = """
PREFIX dance: <http://example.org/dance/>

SELECT ?record (COUNT(?age) AS ?ageCount)
WHERE {
  ?record a dance:DanceRecord .
  OPTIONAL { ?record dance:hasAgeGroup ?age }
}
GROUP BY ?record
HAVING (COUNT(?age) != 1)
ORDER BY ?ageCount
"""
query  = prepareQuery(queries)
result = g.query(query)
pd.DataFrame(result.bindings)

DanceRecords without exactly one AgeGroup: 0

Empty DataFrame
Columns: []
Index: []

## AgeGroup values must only be from the defined set

In [47]:
queries = """
PREFIX dance: <http://example.org/dance/>
PREFIX schema1: <http://schema.org/>

SELECT DISTINCT ?record ?ageLabel
WHERE {
  ?record a dance:DanceRecord ;
          dance:hasAgeGroup ?age .
  ?age schema1:name ?ageLabel .
  FILTER (?ageLabel NOT IN ("Kids"@en, "Teens"@en, "Adults"@en, "Seniors"@en, "All ages"@en))
}
"""
query  = prepareQuery(queries)
result = g.query(query)
pd.DataFrame(result.bindings)

Empty DataFrame
Columns: []
Index: []

## Each DanceRecord must have exactly one TempoRange, and that TempoRange must have both min and max BPM

In [48]:
queries = """
PREFIX dance: <http://example.org/dance/>

SELECT ?record ?tempo ?hasMIn ?hasMax
WHERE {
  ?record a dance:DanceRecord ;
          dance:hasTempoRange ?tempo .
  BIND(EXISTS { ?tempo dance:minTempoBPM ?min } AS ?hasMIn)
  BIND(EXISTS { ?tempo dance:maxTempoBPM ?max } AS ?hasMax)
  FILTER (!?hasMIn || !?hasMax)
}
"""
query  = prepareQuery(queries)
result = g.query(query)
pd.DataFrame(result.bindings)

TempoRanges missing minBPM or maxBPM: 0

Empty DataFrame
Columns: []
Index: []

## A DanceRecord's DanceStyle must itself exist as a typed DanceStyle node

In [49]:
queries = """
PREFIX dance: <http://example.org/dance/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?record ?style
WHERE {
  ?record a dance:DanceRecord ;
          dance:hasDanceStyle ?style .
  FILTER NOT EXISTS { ?style a dance:DanceStyle }
}
"""
query  = prepareQuery(queries)
result = g.query(query)
pd.DataFrame(result.bindings)

Empty DataFrame
Columns: []
Index: []

## A DanceRecord's DanceType must itself exist as a typed DanceType node

In [51]:
queries = """
PREFIX dance: <http://example.org/dance/>

SELECT ?record ?danceType
WHERE {
  ?record a dance:DanceRecord ;
          dance:hasDanceType ?danceType .
  FILTER NOT EXISTS { ?danceType a dance:DanceType }
}
"""
query  = prepareQuery(queries)
result = g.query(query)
pd.DataFrame(result.bindings)

Empty DataFrame
Columns: []
Index: []

## Every DanceStyle node must be referenced by at least one DanceRecord

In [52]:
queries = """
PREFIX dance: <http://example.org/dance/>

SELECT ?style
WHERE {
  ?style a dance:DanceStyle .
  FILTER NOT EXISTS { ?record dance:hasDanceStyle ?style }
}
"""
query  = prepareQuery(queries)
result = g.query(query)
pd.DataFrame(result.bindings)

Empty DataFrame
Columns: []
Index: []

## YTLINK nodes must be connected to a DanceRecord via hasYTLink

In [53]:
queries = """
PREFIX dance: <http://example.org/dance/>

SELECT ?ytlink
WHERE {
  ?ytlink a dance:YTLINK .
  FILTER NOT EXISTS { ?record dance:hasYTLink ?ytlink }
}
"""
query  = prepareQuery(queries)
result = g.query(query)
pd.DataFrame(result.bindings)

YTLINK nodes not linked to any DanceRecord (orphans): 0

Empty DataFrame
Columns: []
Index: []

## YTLINK view count and likes must not be negative

In [54]:
queries = """
PREFIX dance: <http://example.org/dance/>
PREFIX schema1: <http://schema.org/>

SELECT ?ytlink ?prop ?val
WHERE {
  ?ytlink a dance:YTLINK .
  ?ytlink ?prop ?val .
  FILTER (?prop IN (schema1:interactionCount, schema1:UserLikes))
  FILTER (?val < 0)
}
"""
query  = prepareQuery(queries)
result = g.query(query)
pd.DataFrame(result.bindings)

Empty DataFrame
Columns: []
Index: []

## Each DanceRecord must have at least one Instrument, MusicGenre, and HealthBenefit

In [55]:
queries = """
PREFIX dance: <http://example.org/dance/>

SELECT ?record
       (COUNT(DISTINCT ?instrument) AS ?instruments)
       (COUNT(DISTINCT ?genre)      AS ?genres)
       (COUNT(DISTINCT ?benefit)    AS ?benefits)
WHERE {
  ?record a dance:DanceRecord .
  OPTIONAL { ?record dance:hasInstrument ?instrument }
  OPTIONAL { ?record dance:hasAssociatedMusicGenre ?genre }
  OPTIONAL { ?record dance:hasHealthBenefit ?benefit }
}
GROUP BY ?record
HAVING (COUNT(DISTINCT ?instrument) = 0 || COUNT(DISTINCT ?genre) = 0 || COUNT(DISTINCT ?benefit) = 0)
ORDER BY ?record
"""
query  = prepareQuery(queries)
result = g.query(query)
pd.DataFrame(result.bindings)

Empty DataFrame
Columns: []
Index: []

# Interoperability - Hannes

## missing domain

In [29]:
queries = """
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT DISTINCT ?p ?propertyType
WHERE {
  ?p a ?propertyType .
  VALUES ?propertyType { owl:ObjectProperty owl:DatatypeProperty }
  FILTER NOT EXISTS { ?p rdfs:domain ?any }
}
ORDER BY ?propertyType ?p
"""
query  = prepareQuery(queries)
result = g.query(query)
pd.DataFrame(result.bindings)

Empty DataFrame
Columns: []
Index: []

## missing range

In [30]:
queries = """
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT DISTINCT ?p ?propertyType
WHERE {
  ?p a ?propertyType .
  VALUES ?propertyType { owl:ObjectProperty owl:DatatypeProperty }
  FILTER NOT EXISTS { ?p rdfs:range ?any }
}
ORDER BY ?propertyType ?p
"""
query  = prepareQuery(queries)
result = g.query(query)
pd.DataFrame(result.bindings)

Empty DataFrame
Columns: []
Index: []

## missing label (class)

In [31]:
queries = """
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT DISTINCT ?c
WHERE {
  ?c a owl:Class .
  FILTER NOT EXISTS { ?c rdfs:label ?any }
}
"""
query  = prepareQuery(queries)
result = g.query(query)
pd.DataFrame(result.bindings)

Empty DataFrame
Columns: []
Index: []

## missing label (property)

In [32]:
queries = """
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT DISTINCT ?p ?propertyType
WHERE {
  ?p a ?propertyType .
  VALUES ?propertyType { owl:ObjectProperty owl:DatatypeProperty }
  FILTER NOT EXISTS { ?p rdfs:label ?any }
}
ORDER BY ?propertyType ?p
"""
query  = prepareQuery(queries)
result = g.query(query)
pd.DataFrame(result.bindings)

Empty DataFrame
Columns: []
Index: []

## properties used that are not defined in the ontology

In [33]:
# merge KG and ontology into one graph
g_merged = g + g_ontology

queries = """
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT DISTINCT ?p
WHERE {
  ?s ?p ?o .
  FILTER (?p != rdf:type)
  FILTER NOT EXISTS { ?p a owl:ObjectProperty }
  FILTER NOT EXISTS { ?p a owl:DatatypeProperty }
  FILTER NOT EXISTS { ?p a owl:AnnotationProperty }
  FILTER NOT EXISTS { ?p a rdf:Property }
}
ORDER BY ?p
"""
query  = prepareQuery(queries)
result = g_merged.query(query)
pd.DataFrame(result.bindings)

                                                 p
0                    http://schema.org/description
1                           http://schema.org/name
2     http://www.w3.org/2000/01/rdf-schema#comment
3      http://www.w3.org/2000/01/rdf-schema#domain
4       http://www.w3.org/2000/01/rdf-schema#label
5       http://www.w3.org/2000/01/rdf-schema#range
6  http://www.w3.org/2000/01/rdf-schema#subClassOf
7             http://www.w3.org/2002/07/owl#sameAs